const assert = require('assert');
const { initRenderDebugger } = require('../dist/probe/render-debugger');
const { initEnvironment } = require('../dist/probe/environment');
let scene = { uuid: 'scene-a', name: 'Scene' };
const entries = new Map([['save', '{"level":4,"token":"abc123"}'], ['authToken', 'secret'], ['large', 'x'.repeat(3000)], ['url', 'https://host/path?token=secret']]);
const storage = { get length() { return entries.size; }, key: i => [...entries.keys()][i], getItem: k => entries.has(k) ? entries.get(k) : null };
function RenderComponent() {}
RenderComponent.prototype._checkBacth = function () {};
function Director() {}
Director.prototype.mainLoop = function () {};
function Device() {}
Device.prototype.draw = function () {};
function Forward() {}
Forward.prototype._draw = function () {};
const engine = { ENGINE_VERSION: '2.4.7', director: { getScene: () => scene, getTotalFrames: () => 17 },
  RenderComponent, Director, gfx: { Device }, renderer: { _forward: new Forward(), _batcher: { flush() {} } },
  sys: { isNative: false, platform: 101, localStorage: storage }, assetManager: { downloader: { maxConcurrency: 6, token: 'SECRET' } } };
global.window = { cc: engine, CC_DEBUG: true, CC_DEV: false, password: 'SECRET' };
global.document = { getElementById: () => null };
initEnvironment(); initRenderDebugger();
(async () => {
  const env = window.__mcpEnvironment.getEnvironment();
  assert.strictEqual(env.version, '2.4.7');
  assert.strictEqual(env.downloader.maxConcurrency, 6);
  assert(!JSON.stringify(env).includes('SECRET'));
  const keys = window.__mcpEnvironment.readStorage({});
  assert.strictEqual(keys.entries.find(e => e.key === 'save').size, entries.get('save').length);
  assert(!Object.prototype.hasOwnProperty.call(keys.entries[0], 'value'));
  const values = window.__mcpEnvironment.readStorage({ keys: ['save', 'authToken', 'large', 'url', 'missing'] });
  assert(!JSON.stringify(values).includes('abc123'));
  assert(!JSON.stringify(values).includes('secret'));
  assert.strictEqual(values.entries.find(e => e.key === 'large').value.length, 2048);
  assert.strictEqual(values.entries.find(e => e.key === 'large').truncated, true);
  assert.strictEqual(values.entries.find(e => e.key === 'missing').missing, true);
  assert.strictEqual(window.__mcpEnvironment.readStorage({ keys: Array(9).fill('save') }).success, false);
  assert.strictEqual(window.__mcpEnvironment.readStorage({ prefix: '', limit: 10000 }).success, false);
  const original = [RenderComponent.prototype._checkBacth, Director.prototype.mainLoop, Device.prototype.draw, Forward.prototype._draw, engine.renderer._batcher.flush];
  const dbg = window.__mcpRenderDebuggerHook;
  assert.strictEqual(dbg.getSummary({}).available, false);
  const capture = dbg.captureSummary({ durationMs: 50, limit: 2 });
  assert.strictEqual(dbg._isActive, true);
  assert.strictEqual((await dbg.captureSummary({ durationMs: 50 })).error, 'RENDER_CAPTURE_BUSY');
  const component = new RenderComponent();
  component.node = { name: 'Culprit', uuid: 'node-c' };
  component._materials = [{ name: 'new', getHash: () => 2, getProperty: () => 1 }];
  const batcher = { material: { name: 'old', getHash: () => 1 }, cullingMask: 1, node: { name: 'Victim', uuid: 'node-v' }, execute() {}, flush() {} };
  const originalDynamic = [batcher.execute, batcher.flush];
  dbg._currentFrame = { frameId: 17, drawCalls: [] };
  for (let i = 0; i < 4; i++) component._checkBacth(batcher, 1);
  dbg._currentFrame = null;
  const report = await capture;
  assert.strictEqual(report.success, true);
  assert.strictEqual(report.breaks.length, 2);
  assert.strictEqual(report.breaks[0].culpritId, 'node-c');
  assert.strictEqual(report.context.sceneUuid, 'scene-a');
  assert.strictEqual(dbg._isActive, false);
  assert.deepStrictEqual([RenderComponent.prototype._checkBacth, Director.prototype.mainLoop, Device.prototype.draw, Forward.prototype._draw, engine.renderer._batcher.flush], original);
  assert.deepStrictEqual([batcher.execute, batcher.flush], originalDynamic);
  assert.strictEqual(batcher.__mcp_execute_hooked, undefined);
  const dummyCapture = dbg.captureSummary({ durationMs: 50, limit: 8 });
  const dummy = {};
  const oldMaterial = { name: 'sprite', getHash: () => 1 };
  const spriteBatch = { material: oldMaterial, cullingMask: 1, node: dummy, _dummyNode: dummy };
  const back = new RenderComponent();
  back.node = { name: 'Back', uuid: 'back' };
  back._materials = [oldMaterial];
  back._checkBacth(spriteBatch, 1);
  component._checkBacth(spriteBatch, 1);
  const dummyReport = await dummyCapture;
  assert(dummyReport.breaks.some(b => b.culpritId === 'node-c' && b.victimId === 'back'));
  dbg.injectHooks();
  await dbg.captureSummary({ durationMs: 50 });
  assert.strictEqual(dbg._isActive, true);
  const activeCancel = dbg.captureSummary({ durationMs: 500 }, 'active');
  dbg.cancelCapture('active');
  assert.strictEqual((await activeCancel).error, 'RENDER_CAPTURE_CANCELLED');
  assert.strictEqual(dbg._isActive, true);
  dbg.restoreHooks();
  const staleCapture = dbg.captureSummary({ durationMs: 50 });
  scene = { uuid: 'scene-b', name: 'Changed' };
  assert.strictEqual((await staleCapture).error, 'RENDER_CONTEXT_CHANGED');
  assert.strictEqual(dbg._isActive, false);
  const cancelledCapture = dbg.captureSummary({ durationMs: 500 }, 'pending');
  assert.strictEqual(dbg.cancelCapture('pending'), true);
  assert.strictEqual((await cancelledCapture).error, 'RENDER_CAPTURE_CANCELLED');
  assert.strictEqual(dbg._isActive, false);
  dbg.cancelCapture('late');
  assert.strictEqual((await dbg.captureSummary({ durationMs: 50 }, 'late')).error, 'RENDER_CAPTURE_CANCELLED');
  assert.strictEqual(dbg._isActive, false);
  for (let i = 0; i < 64; i++) dbg.cancelCapture('id-' + i);
  assert(dbg._cancelledCaptures.size <= 32);
  dbg._cancelledCaptures.set('expired', Date.now() - 1);
  assert.strictEqual((await dbg.captureSummary({ durationMs: 50 }, 'expired')).success, true);
  const brokenStore = { getItem() { throw new Error('SECRET'); } };
  engine.sys.localStorage = brokenStore;
  assert.strictEqual(window.__mcpEnvironment.readStorage({ keys: ['save'] }).entries[0].error, 'STORAGE_READ_FAILED');
  engine.sys.localStorage = storage;
  const secondEngine = { ...engine, director: { getScene: () => scene } };
  const engineChange = dbg.captureSummary({ durationMs: 50 });
  window.cc = secondEngine;
  assert.strictEqual((await engineChange).error, 'RENDER_CONTEXT_CHANGED');
  assert.deepStrictEqual([RenderComponent.prototype._checkBacth, Director.prototype.mainLoop, Device.prototype.draw, Forward.prototype._draw, engine.renderer._batcher.flush], original);
  window.cc = engine;
  dbg.injectHooks();
  const retained = RenderComponent.prototype._checkBacth;
  const foreign = function () { return retained.apply(this, arguments); };
  RenderComponent.prototype._checkBacth = foreign;
  dbg.restoreHooks();
  assert.strictEqual(RenderComponent.prototype._checkBacth, foreign);
  assert.doesNotThrow(() => component._checkBacth(batcher, 1));
  await dbg.captureSummary({ durationMs: 50 });
  assert.strictEqual(RenderComponent.prototype._checkBacth, foreign);
  RenderComponent.prototype._checkBacth = original[0];
  const replacedCapture = dbg.captureSummary({ durationMs: 50 });
  dbg.restoreHooks();
  dbg.injectHooks();
  const replacement = RenderComponent.prototype._checkBacth;
  assert.strictEqual((await replacedCapture).error, 'RENDER_CAPTURE_INTERRUPTED');
  assert.strictEqual(dbg._isActive, true);
  assert.strictEqual(RenderComponent.prototype._checkBacth, replacement);
  dbg.restoreHooks();
  const claimedCapture = dbg.captureSummary({ durationMs: 50 });
  dbg.injectHooks(); // User enables the debugger while the scoped capture is running.
  assert.strictEqual((await claimedCapture).restoredActive, true);
  assert.strictEqual(dbg._isActive, true);
  dbg.restoreHooks();
  const claimedCancel = dbg.captureSummary({ durationMs: 500 }, 'claimed-cancel');
  dbg.injectHooks();
  dbg.cancelCapture('claimed-cancel');
  assert.strictEqual((await claimedCancel).error, 'RENDER_CAPTURE_CANCELLED');
  assert.strictEqual(dbg._isActive, true);
  dbg.restoreHooks();
  console.log('PASS bounded environment/storage redaction and reversible render captures');
})().catch(error => { console.error(error); process.exitCode = 1; });
